[build]
command = "npm run build"
functions = "functions"
publish = "dist"

[dev]
functions = "functions"
publish = "dist"

[[plugins]]
package = "netlify-plugin-chromium"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[headers]]
for = "/index.html"
[headers.values]
Cache-Control = "public, max-age=3600, stale-while-revalidate=86400"
