[build]
command = "npm run build"
functions = "functions"
publish = "dist"

[functions]
node_bundler = "esbuild"
external_node_modules = ["chrome-aws-lambda"]
included_files = ["node_modules/chrome-aws-lambda/bin/*"]

[dev]
functions = "functions"
publish = "dist"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[headers]]
for = "/index.html"
[headers.values]
Cache-Control = "public, max-age=3600, stale-while-revalidate=86400"
